[package]
name = "h2n5"
version = "0.1.0"
authors = ["Andrew Champion <andrew.champion@gmail.com>"]

[dependencies]
actix-web = "0.4"
image = "0.18"
n5 = "0.1"
ndarray = "0.11"
num-traits = "0.2"
regex = "*"
structopt = "0.2"

[patch.crates-io]
n5 = { git = "https://github.com/aschampion/rust-n5" }
