name: CI
on: [push, pull_request]

env:
  PROJ_NAME: h2n5

jobs:
  test:
    uses: ./.github/workflows/test.yml
    with:
      msrv: 1.56

  publish:
    uses: ./.github/workflows/publish.yml
    needs: [test]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    secrets: inherit

  dist:
    uses: ./.github/workflows/dist.yml
    needs: [publish]
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/v')
    with:
      proj_name: h2n5
    secrets: inherit
